flash_fp_mcu: Add config_nissa
Add FPMCU flash support for nissa

BUG=b:388202473
TEST=On pujjoniru deivce, ran flash_fp_mcu successfully

Change-Id: I18a415bb738fa9ee0b180e9280d3b498f6390d01
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/6179183
Reviewed-by: Jianeng Ceng <cengjianeng@huaqin.corp-partner.google.com>
Reviewed-by: Shou-Chieh Hsu <shouchieh@chromium.org>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Reviewed-by: Yuxiang Zeng <zengyuxiang@huaqin.corp-partner.google.com>
Reviewed-by: Ashley Shen <shenashley@google.com>
Commit-Queue: Jianeng Ceng <cengjianeng@huaqin.corp-partner.google.com>
Tested-by: Jianeng Ceng <cengjianeng@huaqin.corp-partner.google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -1201,6 +1201,49 @@ config_fatcat() {
   esac
 }
 
+config_nissa() {
+  readonly TRANSPORT="SPI"
+  readonly DEVICE="/dev/spidev1.0"
+
+  # Twinlake uses Alderlake-P PCH and hence
+  # exports INTC1057 ACPI ID matching with pinctrl-alderlake.c
+  # See kernel/v6.6/drivers/pinctrl/intel/pinctrl-alderlake.c
+  # for pin name and pin number.
+  # Examine `cat /sys/kernel/debug/pinctrl/INTC1057:00/gpio-ranges` on a
+  # pujjoniru device to determine gpio number from pin number.
+  # For example: GPP_E7, the pin number is 231 from the pinctrl-alderlake.c.
+  # From the gpio-ranges, the gpio value is 320 + (231 - 224) = 327
+
+  local gpiochip_dev_path="pci0000:00/INTC1057:00/gpio"
+  local gpiobase
+  if ! gpiobase=$(get_sysfs_gpiochip_base "${gpiochip_dev_path}"); then
+    echo "Unable to find gpio chip base"
+    return "${EXIT_PRECONDITION}"
+  fi
+
+  readonly GPIO_CHIP="gpiochip${gpiobase}"
+
+  local model
+  model=$(cros_config / name)
+  case "${model}" in
+    (pujjoniru)
+      # FPMCU RST_ODL is on GPP_E7 = 320 + (231 - 224) = 327
+      local gpionrst=327
+      readonly GPIO_NRST=$(( gpionrst + gpiobase ))
+      # FPMCU BOOT0 is on GPP_D0 = 192 + (119 - 119) = 192
+      local gpioboot=192
+      readonly GPIO_BOOT0=$(( gpioboot + gpiobase ))
+      # FP_PWR_EN is on GPP_D2 = 192 + (121-119) = 194
+      local gpiopwren=194
+      readonly GPIO_PWREN=$(( gpiopwren + gpiobase ))
+      ;;
+    *)
+      echo "FPMCU not supported on model ${model}"
+      return "${EXIT_PRECONDITION}"
+      ;;
+  esac
+}
+
 main() {
   local filename="$1"
   local chip_type
