flash_fp_mcu: add support for fatcat
BUG=b:377595986
TEST=CQ

Change-Id: I84ebb3a5c66c944df9ccb76499b7ea6e4e67ae7b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/6157867
Code-Coverage: Michael Questo <questo@google.com>
Reviewed-by: Matt Davis <mattedavis@google.com>
Tested-by: YH Lin <yueherngl@chromium.org>
Commit-Queue: YH Lin <yueherngl@chromium.org>
Code-Coverage: Zoss <zoss-cl-coverage@prod.google.com>
Reviewed-by: Michael Questo <questo@google.com>
Tested-by: Michael Questo <questo@google.com>

diff --git a/util/flash_fp_mcu b/util/flash_fp_mcu
--- a/util/flash_fp_mcu
+++ b/util/flash_fp_mcu
@@ -1146,6 +1146,47 @@ config_brox() {
   esac
 }
 
+config_fatcat() {
+  readonly TRANSPORT="SPI"
+  readonly DEVICE="/dev/spidev0.0"
+
+  # Examine `cat /sys/kernel/debug/pinctrl/INTC1083:00/gpio-ranges` on a
+  # fatcat device to determine gpio number from pin number.
+
+  local gpiochip_dev_path="pci0000:00/INTC10BC:00/gpio"
+  local gpiobase
+  if ! gpiobase=$(get_sysfs_gpiochip_base "${gpiochip_dev_path}"); then
+    echo "Unable to find gpio chip base"
+    return "${EXIT_PRECONDITION}"
+  fi
+
+  readonly GPIO_CHIP="gpiochip${gpiobase}"
+
+  local model
+  model=$(cros_config / name)
+
+  # On fatcat, gpios are split across two base gpio banks:
+  # gpiochip512 and gpiochip560.
+  local gpiobase512=512
+  local gpiobase560=560
+
+  case "${model}" in
+    *)
+      # FPMCU FPS_RST_N(RST_ODL) is on GPP_C15 = 24 + (39 - 24) = 39
+      local gpionrst=39
+      readonly GPIO_NRST=$(( gpionrst + gpiobase512 ))
+
+      # FPMCU FPMCU_FW_UPDATE(BOOT0) is on GPP_E20 = 26 + (46 - 26) = 46
+      local gpioboot=46
+      readonly GPIO_BOOT0=$(( gpioboot + gpiobase560 ))
+
+      # FPMCU_PWREN(FP_PWR_EN) is on GPP_E19 = 26 + (45 - 26) = 45
+      local gpiopwren=45
+      readonly GPIO_PWREN=$(( gpiopwren + gpiobase560 ))
+      ;;
+  esac
+}
+
 main() {
   local filename="$1"
   local chip_type
